title: Codey-stuff
description: Long-winded answers to questions I've had. JavaScript, Angular.js, Node.js, MongoDB, React.js

url: http://barbaraliau.github.io/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: barbaraliau
   twitter: bjliau

